### ISSUE TITLE
add the concept list

### ISSUE THREAD

**Issue by LinguList** [lexibank/walkerarawakan#11]
Can we have the concept list please also be added to conceepticon? It is quite nice to see that this is a dataset with cognates and full BIPA !

**Comment by tresoldi** [comment]
It is only missing the linking to Concepticon, Natalia and I did this a long time ago. I can the see the concept list is already there: https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/Walker-2011-100.tsv

**Comment by SimonGreenhill** [comment]
Should already be in: https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/Walker-2011-100.tsv-metadata.json

**Comment by SimonGreenhill** [comment]
we should remove ./etc/concepts.tsv and update the code too.

**Comment by LinguList** [comment]
excellent, I was checking the datasets for lexicore...

**Comment by SimonGreenhill** [comment]
this may not be a great candidate as the data looks problematic (Fernando O. de Carvalho has a paper he's writing on how dodgy it is).

**Comment by chrzyki** [comment]
Done https://github.com/lexibank/walkerarawakan/commit/c42edf0fe5a2b495e40f7137b3ad41a0eae34560.
